package com.example.export

import com.example.math.Vertex3D
import com.example.math.Triangle3D
import java.io.File
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt

object ModelExporter {

    // Converts vertices and triangular faces into standard OBJ format with Vertex Colors
    fun exportToOBJ(vertices: List<Vertex3D>, triangles: List<Triangle3D>): String {
        val sb = StringBuilder()
        sb.append("# Photo to 3D OBJ Export\n")
        sb.append("# Generated 3D Mesh with Vertex Colors\n\n")

        // Write vertices with RGB color support as decimals [0..1]
        for (v in vertices) {
            val r = v.r / 255f
            val g = v.g / 255f
            val b = v.b / 255f
            sb.append(String.format("v %.5f %.5f %.5f %.4f %.4f %.4f\n", v.x, v.y, v.z, r, g, b))
        }

        sb.append("\n# Faces\n")
        // OBJ index starts at 1
        for (f in triangles) {
            sb.append(String.format("f %d %d %d\n", f.v1 + 1, f.v2 + 1, f.v3 + 1))
        }

        return sb.toString()
    }

    // Converts vertices and faces to ASCII STL format, ideal for 3D printing slicers
    fun exportToSTL(vertices: List<Vertex3D>, triangles: List<Triangle3D>): String {
        val sb = StringBuilder()
        sb.append("solid PhotoTo3DPrintMesh\n")

        for (f in triangles) {
            val v1 = vertices[f.v1]
            val v2 = vertices[f.v2]
            val v3 = vertices[f.v3]

            // Calculate Normal
            val ax = v2.x - v1.x
            val ay = v2.y - v1.y
            val az = v2.z - v1.z

            val bx = v3.x - v1.x
            val by = v3.y - v1.y
            val bz = v3.z - v1.z

            var nx = ay * bz - az * by
            var ny = az * bx - ax * bz
            var nz = ax * by - ay * bx

            val len = sqrt(nx * nx + ny * ny + nz * nz)
            if (len > 0f) {
                nx /= len
                ny /= len
                nz /= len
            } else {
                ny = -1f
            }

            sb.append(String.format("facet normal %.5f %.5f %.5f\n", nx, ny, nz))
            sb.append("  outer loop\n")
            sb.append(String.format("    vertex %.5f %.5f %.5f\n", v1.x, v1.y, v1.z))
            sb.append(String.format("    vertex %.5f %.5f %.5f\n", v2.x, v2.y, v2.z))
            sb.append(String.format("    vertex %.5f %.5f %.5f\n", v3.x, v3.y, v3.z))
            sb.append("  endloop\n")
            sb.append("endfacet\n")
        }

        sb.append("endsolid PhotoTo3DPrintMesh\n")
        return sb.toString()
    }

    // Converts vertices and faces to PLY format (Polygon File Format) with vertex colors and triangles
    fun exportToPLY(vertices: List<Vertex3D>, triangles: List<Triangle3D>): String {
        val sb = StringBuilder()
        sb.append("ply\n")
        sb.append("format ascii 1.0\n")
        sb.append("comment Generated by Photo completed by AI scanner\n")
        sb.append("element vertex ${vertices.size}\n")
        sb.append("property float x\n")
        sb.append("property float y\n")
        sb.append("property float z\n")
        sb.append("property uchar red\n")
        sb.append("property uchar green\n")
        sb.append("property uchar blue\n")
        sb.append("element face ${triangles.size}\n")
        sb.append("property list uchar int vertex_indices\n")
        sb.append("end_header\n")

        // Vertices data
        for (v in vertices) {
            sb.append(String.format("%.5f %.5f %.5f %d %d %d\n", v.x, v.y, v.z, v.r, v.g, v.b))
        }

        // Faces data
        for (f in triangles) {
            sb.append("3 ${f.v1} ${f.v2} ${f.v3}\n")
        }

        return sb.toString()
    }
}
